// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * coverImgLeft field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.coverimgleft
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    coverimgleft: prismicT.ImageField<never>;
    /**
     * coverTitleLeft field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.covertitleleft
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    covertitleleft: prismicT.KeyTextField;
    /**
     * coverDescriptionLeft field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.coverdescriptionleft
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    coverdescriptionleft: prismicT.KeyTextField;
    /**
     * coverDescriptionKRLeft field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.coverdescriptionkrleft
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    coverdescriptionkrleft: prismicT.KeyTextField;
    /**
     * coverImgRight field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.coverimgright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    coverimgright: prismicT.ImageField<never>;
    /**
     * coverTitleRight field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.covertitleright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    covertitleright: prismicT.KeyTextField;
    /**
     * coverDescriptionRight field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.coverdescriptionright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    coverdescriptionright: prismicT.KeyTextField;
    /**
     * coverDescriptionKRRight field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.coverdescriptionkrright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    coverdescriptionkrright: prismicT.KeyTextField;
    /**
     * carouselImg1 field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouselimg1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    carouselimg1: prismicT.ImageField<never>;
    /**
     * carouselTitle1 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseltitle1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseltitle1: prismicT.KeyTextField;
    /**
     * carouselDescription1 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescription1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescription1: prismicT.KeyTextField;
    /**
     * carouselDescriptionKR1 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescriptionkr1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescriptionkr1: prismicT.KeyTextField;
    /**
     * carouselImg2 field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouselimg2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    carouselimg2: prismicT.ImageField<never>;
    /**
     * carouselTitle2 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseltitle2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseltitle2: prismicT.KeyTextField;
    /**
     * carouselDescription2 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescription2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescription2: prismicT.KeyTextField;
    /**
     * carouselDescriptionKR2 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescriptionkr2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescriptionkr2: prismicT.KeyTextField;
    /**
     * carouselImg3 field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouselimg3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    carouselimg3: prismicT.ImageField<never>;
    /**
     * carouselTitle3 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseltitle3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseltitle3: prismicT.KeyTextField;
    /**
     * carouselDescription3 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescription3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescription3: prismicT.KeyTextField;
    /**
     * carouselDescriptionKR3 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescriptionkr3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescriptionkr3: prismicT.KeyTextField;
    /**
     * carouselImg4 field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouselimg4
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    carouselimg4: prismicT.ImageField<never>;
    /**
     * carouselTitle4 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseltitle4
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseltitle4: prismicT.KeyTextField;
    /**
     * carouselDescription4 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescription4
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescription4: prismicT.KeyTextField;
    /**
     * carouselDescriptionKR4 field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.carouseldescriptionkr4
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    carouseldescriptionkr4: prismicT.KeyTextField;
    /**
     * ourClientsImg field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.ourclientsimg
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    ourclientsimg: prismicT.ImageField<never>;
}
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for Portfolio documents */
interface PortfolioDocumentData {
    /**
     * thumbnail field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * description field in *Portfolio*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * descriptionKR field in *Portfolio*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.descriptionkr
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    descriptionkr: prismicT.KeyTextField;
    /**
     * category field in *Portfolio*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    category: prismicT.KeyTextField;
    /**
     * tag1 field in *Portfolio*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.tag1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tag1: prismicT.KeyTextField;
    /**
     * tag2 field in *Portfolio*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.tag2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tag2: prismicT.KeyTextField;
    /**
     * tag3 field in *Portfolio*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.tag3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tag3: prismicT.KeyTextField;
    /**
     * detailImg1 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg1
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg1: prismicT.ImageField<never>;
    /**
     * detailImg2 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg2: prismicT.ImageField<never>;
    /**
     * detailImg3 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg3
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg3: prismicT.ImageField<never>;
    /**
     * detailImg4 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg4
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg4: prismicT.ImageField<never>;
    /**
     * detailImg5 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg5
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg5: prismicT.ImageField<never>;
    /**
     * detailImg6 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg6
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg6: prismicT.ImageField<never>;
    /**
     * detailImg7 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg7
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg7: prismicT.ImageField<never>;
    /**
     * detailImg8 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg8
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg8: prismicT.ImageField<never>;
    /**
     * detailImg9 field in *Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio.detailimg9
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    detailimg9: prismicT.ImageField<never>;
}
/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PortfolioDocumentData>, "portfolio", Lang>;
export type AllDocumentTypes = HomeDocument | PortfolioDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocument, PortfolioDocumentData, PortfolioDocument, AllDocumentTypes };
    }
}
